sudo: false
language: java
services:
- docker
cache:
  directories:
  - "$HOME/.cache"
env:
  global:
  - MAVEN_HOME=/usr/local/maven-3.3.9

before_install: "cp ./keys/pubring.gpg $HOME/.gnupg/pubring.gpg && cp ./keys/secring.gpg $HOME/.gnupg/secring.gpg && cp ./keys/trustdb.gpg $HOME/.gnupg/trustdb.gpg "

script: "cp .travis.settings.xml $HOME/.m2/settings.xml && mvn deploy -DskipTests && mvn site"
